UoB-COMSM0166/2025-group-16

README.md

Base on week4's labs and homework, add epics & user stories to readme.
- Add Jira and related document's link to readme.

[TG-25] docs: add epics & user stories to readme

---

README.md

- add github workflow link to readme

[TG-29] docs: add github workflow link to readme

---

README.md

One of a w4 homework, adding stakeholder list to readme 
Add stakeholder list to readme

docs: add stakeholder list

---

.vscode/extensions.json

- chore: add p5-vscode to recommended extension list
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-22)

[TG-22] chore: add p5-vscode to recommended extension list

---

README.md

Add Reflection
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-24)

[TG-24]docs: add Reflection

---

docs/README.md
docs/assets/images/entity.svg
docs/index.html
docs/src/classes/Button.js
docs/src/classes/Entity.js
docs/src/classes/Player.js
docs/src/classes/Robot.js
docs/src/classes/SVGImage.js
docs/src/classes/Text.js
docs/src/classes/UIComponent.js
docs/src/classes/button.js
docs/src/classes/entity.js
docs/src/classes/player.js
docs/src/classes/robot.js
docs/src/classes/text.js
docs/src/config/constants.js
docs/src/config/resources.js
docs/src/config/settings.js
docs/src/config/theme.js
docs/src/pages/BasePage.js
docs/src/pages/Results.js
docs/src/pages/Welcome.js
docs/src/pages/basePage.js
docs/src/pages/maps/MapBasicGame.js
docs/src/pages/maps/MapBasicIntro.js
docs/src/pages/maps/mapBasicGame.js
docs/src/pages/maps/mapBasicIntro.js
docs/src/pages/results.js
docs/src/pages/welcome.js
docs/src/sketch.js

- Add svgImage class in order to make importing svg more easier
- Change entity (player, robot) into svg image
- feat: add UIComponent and change class files' names
- style: rename class files into capitalize format
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-52)

[TG-52] feat: add svgImage class & entity image

---

docs/src/sketch.js
docs/style.css

- feat: make game canvas resize according to the window size
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-52)

[TG-52] feat: make game canvas resize according to the window size

---

docs/README.md
docs/src/classes/Button.js
docs/src/classes/Entity.js
docs/src/classes/Robot.js
docs/src/classes/SVGImage.js
docs/src/config/constants.js
docs/src/config/resources.js
docs/src/config/theme.js
docs/src/pages/Results.js
docs/src/pages/Welcome.js
docs/src/pages/maps/MapBasicGame.js
docs/src/pages/maps/MapBasicIntro.js
docs/src/sketch.js

- feat: change name of the game to 'Unstoppable'
- feat: update theme palette
- refactor: adjust resources structure and comments
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-71)

[TG-71] feat: change name of the game & update theme

---

README.md

Add a paragraph in README.md about Final Idea
- Add Final Idea in README.md
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/<TG-18>)

[TG-18] docs: add Final Idea

---

docs/src/pages/maps/BaseMapGame.js

Edited BaseGameMap, add the character lists when the game is played
Edited drawAvatar function, and "Fight" image haven't been updated. Minor change is required after that image is provided.
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-55)

feat: add character list

---

docs/src/config/resources.js
docs/src/pages/maps/BaseMapGame.js

Modify loading image (player list)
add path to Resources
Resources.images.playerlist[pIdx + 1] can directly access the player image
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-55)

[TG-55-fix3] Modify loading image (player list)

---

docs/assets/images/welcomepage/text_loading.svg

- fix: loading text gap
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-74)

[TG-74-2] fix: loading text gap

---

docs/README.md

- docs: add detail of adding image

docs: add detail of adding image

---

docs/index.html
docs/src/pages/Welcome.js
docs/src/pages/WelcomeIntro.js

feat: add intro to welcome page (Susan)
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-54)

[TG-54 ]feat: add welcomeIntro

---

docs/src/config/resources.js
docs/src/pages/Welcome.js
docs/src/pages/maps/MapIntro1.js

- fix: welcomepage typing error 
- adjust if statement to use config setting
- fix: mapIntro1 introduction role position
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-79)

[TG-79] fix: mapIntro1 introduction role position 

---

docs/src/classes/Player.js
docs/src/pages/Welcome.js
docs/src/pages/WelcomeIntro.js

fix: remove shadow, delay=0, keycode==all key
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-54)

Tg 54 fix2

---

docs/src/classes/Button.js
docs/src/classes/Player.js
docs/src/classes/Sound.js
docs/src/classes/Text.js
docs/src/config/resources.js
docs/src/pages/BasePage.js
docs/src/pages/Results.js
docs/src/pages/Welcome.js
docs/src/pages/WelcomeIntro.js
docs/src/pages/maps/BaseMapGame.js
docs/src/pages/maps/BaseMapIntro.js
docs/src/pages/maps/MapGame1.js
docs/src/pages/maps/MapIntro1.js
docs/src/sketch.js
docs/src/state/controller.js
docs/src/state/store.js

- feat: add bgm to each page
- fix: isolate page drawing with graphics context
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-67-2)

[TG-67-2] feat: add bgm to each page

---

docs/src/pages/maps/MapIntro1.js

fix: change the press range.
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-61)

[TG61-3] fix: change the press range.

---

docs/src/pages/Welcome.js

When each player arrived at 'COME HERE', change status to 'OK'
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-89)

fix: When each player arrived at 'COME HERE', change status to 'OK'

---

docs/src/pages/Welcome.js

fix:count down to start game
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-110)

fix:count down to start game

---

docs/src/classes/Entity.js

- fix: delay attack sound
- Reason: In order to play sound according to the target, it need to loop through all the entities first which cause delay.
- Solution: change steps to [check target first -> play sound -> play animation] to avoid delay feeling
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-92)

[TG-92] fix: delay attack sound

---

docs/index.html
docs/src/classes/Entity.js
docs/src/classes/PlayerList.js
docs/src/classes/Text.js
docs/src/pages/maps/BaseMapGame.js

Add a new class 'PlayerList' and draw on BaseMapGame. Still need to draw it on WelcomePage.
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-84)

feat: add PlayerList class and draw on BaseMapGame

---

docs/src/classes/Entity.js
docs/src/classes/Player.js
docs/src/classes/Robot.js
docs/src/config/settings.js
docs/src/pages/maps/BaseMapGame.js

- feat: add dying animation
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-90)

[TG-90] feat: add dying animation

---

docs/src/classes/Entity.js
docs/src/classes/Player.js
docs/src/config/constants.js
docs/src/config/settings.js
docs/src/pages/Welcome.js
docs/src/pages/maps/MapGame2.js

- feat: add MapGame2 playing mechanism (background design not updated yet)
- feat: add temporary shortcuts, developer can press '1' or '2' to jump to game page when on Welcome page
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-103)

[TG-103] feat: add MapGame2 playing mechanism (background design not updated yet)

---

docs/index.html

Font link on html file can work now
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-119)

Fix: undo command on font link

---

docs/src/classes/Button.js
docs/src/pages/BasePage.js
docs/src/pages/maps/MapGame2.js
docs/src/pages/maps/MapIntro1.js
docs/src/state/controller.js
docs/src/state/store.js

- fix: bgm fail to play sometimes
- fix(Button): wrong hover area
- fix(MapGame2): robot should stop hit after win
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-112)

[TG-112] fix: bgm fail to play sometimes

---

docs/assets/images/entity/player_lose.svg

Add player lose svg that have used yarn node merge-svg.js to merge
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-69)

feat: Add a player lose svg file

---

docs/index.html

feat: add page title

---

docs/index.html
docs/src/classes/Entity.js
docs/src/classes/Player.js
docs/src/classes/Robot.js
docs/src/config/settings.js
docs/src/pages/Welcome.js
docs/src/pages/maps/BaseMapGame.js
docs/src/pages/maps/MapGame3.js
docs/src/pages/maps/MapIntro1.js
docs/src/pages/maps/MapIntro3.js
docs/src/utils/checkOutOfBoundary.js

- feat: add MapGame3 playing mechanism (background design not updated yet)
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-104)

[TG-104] feat: add MapGame3 playing mechanism (background design not updated yet)

---

docs/assets/images/entity/player_lose.svg
docs/src/config/resources.js
docs/src/config/theme.js
docs/src/pages/Results.js
docs/src/pages/maps/BaseMapGame.js
docs/src/state/controller.js
docs/src/state/store.js

- feat: update design of result page
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-70)

[TG-70] feat: update design of result page

---

docs/src/classes/Player.js
docs/src/config/settings.js
docs/src/pages/Welcome.js
docs/src/pages/WelcomeIntro.js
docs/src/pages/maps/BaseMapGame.js

- feat: change player2's control back to '/'
- Use "left shift" as control button can cause problems on some different kinds of keyboards, change it back to '/' to have better support for all users
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-86)

[TG-86-2] feat: change player2's control back to '/'

---

docs/src/pages/Results.js

- fix(Results): no loser animation

fix(Results): no loser animation

---

docs/src/config/settings.js
docs/src/pages/Welcome.js

fix: welcomepage change player position to be fixed
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-111)

fix: welcomepage change player position to be fixed

---

docs/src/classes/Entity.js
docs/src/config/resources.js
docs/src/config/settings.js
docs/src/pages/Welcome.js
docs/src/pages/maps/MapGame2.js

- feat(MapGame2): add background

feat(MapGame2): add background

---

docs/src/classes/Entity.js

- fix(Entity): sync hit sound with fist

fix(Entity): sync hit sound with fist

---

docs/src/classes/PlayerList.js
docs/src/classes/Text.js
docs/src/pages/Welcome.js

refactor: player list inherit 'Playerlist' component
- Adjust text class
- PlayerList class add `updateStatus` function
- Adjust PlayerAvatars spacing
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-118)

refactor: player list inherit 'Playerlist' component

---

README.md

Edit README.md which includes two difficulty to our game
Edit README.md which includes two difficulty to our game
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-91)

docs: add two difficuty of our game

---

README.md

Add evaluations
Add two evaluations, which includes quantitative evaluation and qualitative evaluation. Also corresponding solution are provided in the README.md .
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-95)

docs: add evaluation

---

docs/src/classes/Text.js
docs/src/pages/Welcome.js

fix: when player leave gamestartArea, cancel count down
- Adjust `countdown` related code
- Add text doc 
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-124)

[TG-124]fix:when player leave gamestartArea, cancel count down

---

docs/src/pages/maps/MapIntro1.js

Map intro keep pressing any keys will cause flash
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-99)

[TG-100] Fix: Map intro keep pressing any keys will cause flash

---

docs/src/classes/Entity.js
docs/src/config/constants.js
docs/src/pages/Welcome.js

fix:player add animation effect when being attacked and keeping alive
- Add FAKEDIED type, after blinking effect become ALIVE again
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-117)

[TG-117]fix:player add animation effect when being attacked and keeping alive

---

docs/assets/images/welcomepage/player_avatar_lose.svg

Add lose avatar svg file
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-125)

feat: Add lose avatar svg

---

docs/src/classes/PlayerList.js
docs/src/config/resources.js
docs/src/pages/Welcome.js
docs/src/pages/maps/BaseMapGame.js

feat: add lose player status
- add lose player status
- add playerlist class doc.
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-126)

[TG-126] feat: add lose player status

---

docs/src/pages/Results.js

- feat(Results): change title to Result
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-127)

[TG-127] feat(Results): change title to Result

---

docs/src/pages/maps/BaseMapGame.js

- fix: stuck in game when players die at the same time
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-41)

[TG-41] fix: stuck in game when players die at the same time

---

docs/src/pages/maps/BaseMapGame.js

- fix: stuck in game when players die at the same time 2
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-128)

[TG-128] fix: stuck in game when players die at the same time 2

---

docs/src/pages/maps/MapIntro1.js

fix : mapintro one design change

fix : mapintro one design change

---

docs/src/pages/Tutorial.js

fix(Tutorial): no music

---

docs/src/utils/checkKnockedDown.js

- feat: change hit logic
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-132)

[TG-132] feat: change hit logic

---

docs/src/pages/maps/BaseMapGame.js

- feat: show countdown when game start
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-133)

[TG-133] feat: show countdown when game start

---

docs/src/classes/Player.js
docs/src/pages/maps/MapGame2.js

- fix(BaseMapGame): should pause player when counting down
- fix(MapGame2): wrong map range

fix: wrong map range on MapGame2 & pause player when counting down

---

docs/src/classes/Player.js

- fix(Player): should not hit when isPaused

fix(Player): should not hit when isPaused

---

docs/src/utils/countdownManager.js

fix:countdownManager.js

---

docs/src/utils/checkKnockedDown.js

- feat(checkKnockedDown): check base on fist position

feat(checkKnockedDown): check base on fist position

---

docs/src/pages/maps/BaseMapGame.js

- fix(BaseMapGame): playerList fail to show when no winner

fix(BaseMapGame): playerList fail to show when no winner

---

docs/assets/images/welcomepage/icon_soundsoff.svg
docs/assets/images/welcomepage/icon_soundson.svg
docs/assets/images/welcomepage/icon_tutorial.svg
docs/assets/images/welcomepage/text_comehere_v2.svg
docs/assets/images/welcomepage/tileset_square_comehere_v2.svg

upload new svg for welcome page
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-135)

feat: upload new svg for welcome page

---

docs/assets/images/entity/player_jump.svg
docs/assets/images/entity/player_wave_1.svg
docs/assets/images/entity/player_wave_2.svg
docs/assets/images/welcomepage/player_avatar.svg

Add result svg
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-141)

feat: add result page player jump and wave svg

---

README.md

Add Quantitative Evaluation to README.
Add Evaluation results, Evaluation part is all done.
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-144)

docs: Add Quantitative Evaluation to README.

---

README.md

docs: Add three technical challenges and integrate with two difficulty level
Small modifications about three technical challenges and the other part of README
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-140)

docs: Add three technical challenges and integrate with two difficulty level

---

docs/src/pages/maps/BaseMapIntro.js
docs/src/pages/maps/MapIntro1.js
docs/src/pages/maps/MapIntro2.js
docs/src/pages/maps/MapIntro3.js
docs/src/pages/maps/MapIntro4.js
docs/src/pages/maps/MapIntro5.js
docs/src/pages/maps/MapIntro6.js

Feat : refine BaseMapIntro and other intros.
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-155)

[TG-155]feat : refine BaseMapIntro and other intros

---

docs/src/config/settings.js
docs/src/pages/maps/BaseMapIntro.js
docs/src/pages/maps/MapIntro1.js
docs/src/pages/maps/MapIntro2.js
docs/src/pages/maps/MapIntro3.js
docs/src/pages/maps/MapIntro4.js
docs/src/pages/maps/MapIntro5.js
docs/src/pages/maps/MapIntro6.js

- fix: adjust baseIntro to resolve conflict

fix: adjust baseIntro to resolve conflict

---

docs/src/pages/maps/BaseMapIntro.js
docs/src/pages/maps/MapIntro1.js

- fix: adjust control text to origin layout
- fix: add countdown back

fix: base map intro

---

docs/src/classes/Sound.js
docs/src/pages/BasePage.js
docs/src/pages/Welcome.js
docs/src/sketch.js
docs/src/state/controller.js
docs/src/state/store.js

fix: speaker status store global status
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-143)

[Tg-143] fix: speaker status store global status

---

README.md

doc: sustainability session
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-156)

[TG-156]doc:sustainability session

---

docs/src/classes/Player.js
docs/src/classes/PlayerList.js
docs/src/pages/maps/BaseMapGame.js

feat:Add player CD time on playerlist
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-96)

[TG-96] feat:Add player CD time on playerlist

---

docs/src/pages/maps/MapGame3.js

- feat(MapGame3): adjust map boundary
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-129)

[TG-129] feat(MapGame3): adjust map boundary

---

docs/src/pages/maps/BaseMapGame.js
docs/src/pages/maps/MapGame6.js

1. Edit BaseMapGame - add Override for entity.draw
2. Edit MapGame6 - Basic swap player logic is done!
1. Edit BaseMapGame - add Override for entity.draw
2. Edit MapGame6 - Basic swap player logic is done!
3. 
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-190)

feat: game 6 basic logic

---

README.md

doc: README modification
doc: README modification
NASA TLX table and some descriptions 
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-191)

doc: README modification

---

README.md

Modify Figure, Table
Modify Figure, Table
using HTML!!
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-191)

doc: Modify Figure, Table.

---

README.md

fix doc about figures and tables
check html about figures and tables in README
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-191)

docs: fix figure and tables

---

README.md

fix Figure 1 
fix Figure 1 in README
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-191)

fix: doc figure:)

---

docs/src/pages/maps/MapGame5.js

ya! I've done the map 5 developement!
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-163)

faet(MapGame5): Deveplop 321 attack map

---

docs/src/classes/Dialog.js
docs/src/classes/welcome/RulesSettingDialog.js
docs/src/classes/welcome/TutorialDialog.js
docs/src/pages/BasePage.js
docs/src/pages/Tutorial.js
docs/src/pages/Welcome.js
docs/src/pages/maps/BaseMapGame.js

- refactor(Dialog): reuse logic in TutorialDialog and RulesSettingDialog
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-157)

refactor(Dialog): reuse logic in TutorialDialog and RulesSettingDialog

---

docs/src/classes/Robot.js
docs/src/pages/maps/MapGame4.js
docs/src/pages/maps/MapGame5.js

feat: init dance map logic
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-161)

[TG-161] feat: init dance logic

---

docs/src/pages/maps/MapIntro1.js
docs/src/pages/maps/MapIntro2.js
docs/src/pages/maps/MapIntro3.js

Updated the Desert, Grass and Jail map intro.
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-113)

feat: update map intros for Desert, Grass and Jail.

---

docs/src/pages/maps/MapIntro6.js

Introduced a new map intro for level 6.
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-166

TG-166: Add intro for Map 6

---

docs/src/pages/maps/MapGame4.js

fix:Adjust Dance Map effect to fit the map
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-181)

[TG-181] fix:Adjust Dance Map effect to fit the map

---

docs/src/pages/maps/BaseMapGame.js
docs/src/pages/maps/MapGame6.js

Fixed missing background music and speaker icon on Map6, which were hidden behind the newly added background.
- MapGame6: updated draw() method for a clearer version.
- BaseMapGame: modified it to include an empty item placeholder for Game 6 (for placing magic circle above background and below characters).
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-162

fix: no background music and icon on Map6

---

README.md

test: add manual testing report
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-188)

[TG-188] test: add manual testing report

---

docs/src/config/constants.js
docs/src/config/resources.js
docs/src/pages/MapSelection.js

- feat(MapSelection): add 3 more options
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-168)

[TG-168] feat(MapSelection): add 3 more options

---

docs/src/classes/Sound.js
docs/src/pages/maps/BaseMapGame.js

- feat(BaseMapPage): add countdown sound
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-206)

[TG-206] feat(BaseMapPage): add countdown sound

---

docs/src/pages/maps/MapIntro4.js

[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-164)

[TG-164]feat: add intro to map4

---

README.md

- docs: adjust process section & add developer readme link
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-186)

[TG-186] docs: adjust process section & add developer readme link

---

README.md

Revise README
Basically final version is here, only conclusion need to be added.
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-180)

docs: revise readme file

---

README.md

我的名字拼反嚕 讓我改一下
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/)

correct the error of spelling my name

---

docs/index.html
docs/src/classes/Sound.js
docs/src/classes/SpeakerIconButton.js
docs/src/pages/BasePage.js

- fix: mute all sounds when speaker is mute
- move all speaker related code to SpeakerIconButton class
- use global state `Store.speakerOn` to control SpeakerIconButton state
- use p5.js `outputVolume` to control mute/unmute function
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-207)

[TG-207] fix: mute all sounds when speaker is mute

---

docs/src/pages/maps/MapGame6.js

fix: Map6 logic issue
1. Modify game logic.
2. Change the number of robots in Map6 from 10 to 20.
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-209

TG-209: fix Map6 issue

---

README.md

- docs: update sequence diagram
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-179)

[TG-179-2] docs: update sequence diagram

---

README.md

- docs: update 'process' with partial info from developer readme
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-179)

[TG-179-2] docs: update 'process' with partial info from developer readme

---

README.md

- docs: update 'process' section
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-179)

[TG-179-3] docs: update 'process' section

---

README.md

[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/)

[TG-120-2]feat: change gifs in README"

---

docs/README.md

- docs: add coding styles instruction
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-186)

[TG-186-2] docs: add coding styles instruction

---

docs/src/pages/maps/MapGame6.js

fix: update robot number: 20 -> 25
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-209

fix: update robot number: 20 -> 25

---

docs/src/pages/MapSelection.js

- fix(MapSelection): change scroll direction
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-214)

[TG-214] fix(MapSelection): change scroll direction

---

docs/assets/images/mapSelection/icon_exit.svg

add exit botton design
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-215)

feat: add the exit botton svg

---

README.md

doc: strong bold words were fixed
Just change some of the <strong> which make our documentation look weird.
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-220)

doc: strong issue fixed

---

docs/src/pages/maps/MapGame3.js

[TG-189] fix: Map3 boundary

---

docs/src/pages/maps/MapIntro2.js
docs/src/pages/maps/MapIntro3.js
docs/src/pages/maps/MapIntro4.js
docs/src/pages/maps/MapIntro5.js
docs/src/pages/maps/MapIntro6.js

Refine description of rules for Map2 to Map 6 intro
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-212

fix: Refined description of rules for Map2 to Map 6 intro

---

README.md

add Video Demonstration to Readme
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-184)

[TG-184]feat: add Video Demonstration to Readme

---

README.md

docs: fix some wrong words
(docs: fix some wrong words)
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-221)

docs: fix some Readme weird parts:))

---

README.md

Modification part:
Heuristic Evaluation
3.6, 3.7 ---
Modification part:
Heuristic Evaluation
3.6, 3.7 ---
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/TG-221-2)

docs:Fan's modification

---

README.md

review design and implement part

doc:review design and implement

---

README.md

docs: update readme 3.8&3.9.
1. 3.8: Update team reflection and structure.
2. 3.9: Add note explaining our effort weight.
3. 3.9: Add <br> between members' English name and Chinese name.
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/)

docs: update readme 3.8&3.9

---

README.md

add sus survey table and finding
[View Jira Ticket](https://vivi2393142-0702.atlassian.net/browse/)

add sus survey table and finding

---

docs/src/pages/Tutorial.js

- fix(Tutorial): fail to finish progress when exceed

fix(Tutorial): fail to finish progress when exceed
